services:
  # 1. Base de datos PostgreSQL
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1212
      POSTGRES_DB: distribuidosBD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d distribuidosBD" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Backend Spring Boot
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev

    container_name: spring_backend
    restart: always
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/distribuidosBD
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1212
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      BONITA_URL: ${BONITA_URL:-http://host.docker.internal:8081/bonita}
      BONITA_USERNAME: ${BONITA_USERNAME:-install}
      BONITA_PASSWORD: ${BONITA_PASSWORD:-install}
    volumes:
      - ./backend:/app
      - maven_cache:/root/.m2
    depends_on:
      db:
        condition: service_healthy

  # 3. Frontend Angular
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev

    container_name: angular_frontend
    restart: always
    ports:
      - "4200:4200" # Acceso en http://localhost:4200
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
  maven_cache:
